/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.1/samples
 */

plugins {
    id("java")
    id("application")
}

group = "gamebot"
version = "1.0.0"

repositories {
    mavenCentral()
}

application {
    mainClass.set("gamebot.Main")
}
