/*
 * This source file was generated by the Gradle 'init' task
 */
package gamebot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertEquals(1, 1);
    }
}
